#!/bin/bash
REPO_URL=$1;
TEMP_DIR=$2;
REPO_PATH=$3;

REPO_DIR=$TEMP_DIR/proj;
JSON_DIR=$TEMP_DIR/json;

VAST=$JSON_DIR/vast.json;
TMAP=$JSON_DIR/tmap.json;
TM3D=$JSON_DIR/tm3d.json;

if [ -z "$REPO_URL" ] || [ -z "$TEMP_DIR" ]; then
  cat usage.txt;
  exit 1;
fi

echo "Cleaning $TEMP_DIR";
mkdir -p $TEMP_DIR;
rm -rf $TEMP_DIR/*;
mkdir -p $JSON_DIR;

PATH=node_modules/.bin:$PATH;

if [[ "$REPO_URL" =~ [^hn:] ]]; then
  echo "Downloading HN comments from $REPO_URL and generating AST in $VAST";
  hn-ast $REPO_URL $TEMP_DIR $VAST || exit 1;
else
  echo "Cloning sources into $REPO_DIR";
  (GIT_TERMINAL_PROMPT=0 git clone \
    --depth 1 \
    --shallow-submodules \
    --no-tags \
    $REPO_URL $REPO_DIR) || exit 1;
  echo "Parsing TS and generating AST in $VAST";
  ast-typescript -p $REPO_DIR/$REPO_PATH > $VAST || exit 1;
fi

echo "Converting AST into a treemap in $TMAP";
treemap-ast $VAST > $TMAP || exit 1;

echo "Generating a 3D treemap layout in $TM3D";
webgl-3d-treemap $TMAP > $TM3D || exit 1;
