#!/bin/bash
DATA_SRC=$1;
WORK_DIR=$2;
OUT_FILE=$3;

GITHUB_BASE="https://github.com/";

REPO_DIR=$WORK_DIR/proj;
JSON_DIR=$WORK_DIR/json;

VAST=$JSON_DIR/vast.json;
TMAP=$JSON_DIR/tmap.json;
TM3D=$JSON_DIR/tm3d.json;

if [ -z "$DATA_SRC" ] || [ -z "$WORK_DIR" ]; then
  cat usage.txt;
  exit 1;
fi

echo "Cleaning $WORK_DIR";
mkdir -p $WORK_DIR;
rm -rf $WORK_DIR/*;
mkdir -p $JSON_DIR;

PATH=node_modules/.bin:$PATH;

if [[ $DATA_SRC =~ ^hn: ]]; then
  echo "Downloading HN comments from $DATA_SRC";
  hn-ast $DATA_SRC $WORK_DIR $VAST || exit 1;
fi

if [[ $DATA_SRC =~ ^github: ]]; then
  GIT_URL="${DATA_SRC/github:/$GITHUB_BASE}";
  echo "Cloning sources from $GIT_URL";
  (GIT_TERMINAL_PROMPT=0 git clone \
    --depth 1 \
    --shallow-submodules \
    --no-tags \
    $GIT_URL $REPO_DIR) || exit 1;
  echo "Parsing TS and generating AST in $VAST";
  ast-typescript -p $REPO_DIR > $VAST || exit 1;
fi

echo "Converting AST into a treemap in $TMAP";
treemap-ast $VAST > $TMAP || exit 1;

echo "Generating a 3D treemap layout in $TM3D";
webgl-3d-treemap $TMAP > $TM3D || exit 1;

if [ -z "$OUT_FILE" ]; then
  cat $TM3D;
else
  echo "Copying the 3D treemap to $OUT_FILE";
  mkdir -p $(dirname $OUT_FILE);
  cp $TM3D $OUT_FILE;
fi
